### ISSUE TITLE
behavior when XLEN less than widest supported XLEN

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-zfinx#10]
This is a bit esoteric, but can you please clarify the expected behavior for Zfinx destination registers when XLEN is less than the widest supported XLEN? The Privileged Specification says this about X registers:

_Whenever XLEN in any mode is set to a value less than the widest supported XLEN, all operations must ignore source operand register bits above the configured XLEN, and must sign-extend results to fill the entire widest supported XLEN in the destination register._

The Unprivileged Specification then says this about floating point results:

_When multiple floating-point precisions are supported, then valid values of narrower n-bit types, n < FLEN, are represented in the lower n bits of an FLEN-bit NaN value, in a process termed NaN-boxing. The upper bits of a valid NaN-boxed value must be all 1s._

Suppose we are executing with XLEN=32 on a core that also supports XLEN=64, and a single-precision result is generated. Would you expect the 64-bit result register to be sign-extended or NaN boxed?

**Comment by tariqkurd-repo** [comment]
Wow, that really is a corner case. I don't know if real implementations actually make misa.mxl programmable. This could get quite tricky, for example an RV64D core with misa.mxl=32 would revert to using register pairs for the double precision data, and then each half will need to be sign-extended or Nan-boxed out to 64-bits. If the written number includes the top of the FP data then it's easy to argue that you NaN box it, but for the bottom half, it's not so clear.

So I would say NaN-box to XLEN bits, but NaN-boxing the lower half of the data in that weird case makes no sense. I'll put an email on the mailing list and get back to you.

**Comment by JamesKenneyImperas** [comment]
Thanks Tariq, I'll wait for feedback. For now I've assumed it is NaN-boxed.

For your information, I think we are in a position this week to create a riscvOVPsim release that implements all of this current specification, including the 8 architecture options in table 1 and Zfinx with the V extension too (for that, I've assumed that all vector instructions remain implemented; that can easily be corrected later). We can let you know when it is available if you are interested.

**Comment by JamesKenneyImperas** [comment]
On further consideration, I think the only thing that makes sense is to NaN-box to the _current_ XLEN (if required) and then sign-extend affected registers to the _widest supported_ XLEN.

**Comment by tariqkurd-repo** [comment]
I think you're right, and conveniently there's no difference  in actual behaviour - it's just "fill the upper bits with 1" as you're sign extending from the nan box, the top bit of which is 1. I'll confirm ASAP

**Comment by JamesKenneyImperas** [comment]
The behaviour _would_ differ for single-precision results with the top bit set in the scenario I stated in the original post, but I think my later proposal sounds right and is simple to articulate.

**Comment by tariqkurd-repo** [comment]
yes, you're right. I'm documenting that now (I realised my mistake after submitting the comment)

**Comment by tariqkurd-repo** [comment]
ok, documented, plesae check it!

Tariq

**Comment by JamesKenneyImperas** [comment]
Yes, that looks like what I would expect. Thanks!

**Comment by tariqkurd-repo** [comment]
Hi @JamesKenneyImperas we now have the proposal for Zfinx to include in the ISA manual: https://github.com/riscv/riscv-zfinx/blob/master/zfinx-spec-20210511-0.41.pdf

Can you check your implementation against it? I think the only question is whether misa.[FDQ] is hardwired to zero, as that's the only change this year.
