### ISSUE TITLE
Zqinx for XLEN=128?

### ISSUE THREAD

**Issue by RoastVeg** [riscv/riscv-zfinx#11]
If I understand correctly, isn't there a space for a Zqinx extension to RV128I? Other than a lack of interest, is there a particular reason why it isn't included yet? I would imagine an RV128IVZqinx hart to be quite an interesting design concept.

**Comment by tariqkurd-repo** [comment]
We decided to exclude Zqinx. One reason is lack of interest. Another is that Rv32Zqinx causes register-quads as oppose to register pairs. It is possible to add it in the future if there is any interest.
