### ISSUE TITLE
Zhinx should be Zfhinx

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-zfinx#12]
Zfinx is analogous to F, Zdinx is analogous to D and Zhinx is analogous to Zfh so surely should be called Zfhinx unless Zfh is being renamed to Zh? Otherwise it looks like a user-level extension related to H, the hypervisor extension.

**Comment by tariqkurd-repo** [comment]
@aswaterman set the name of the extension so I'll let him comment.

**Comment by aswaterman** [comment]
Actually, I didn't, but I don't have any problem with the name.

**Comment by kasanovic** [comment]
Should be Zfhinx.  Zh* will be more confusing, and take more namespace.  Trying to keep scalar FP extensions in Zf*/Zfd*/Zfq* namespaces.

**Comment by tariqkurd-repo** [comment]
Zfhinx / Zfhinxmin does seem more regular - extension name + inx

**Comment by tariqkurd-repo** [comment]
the decision was taken to keep the name as Zhinx

**Comment by jrtc27** [comment]
By?

**Comment by tariqkurd-repo** [comment]
Andrew, and the spec has passed public review

**Comment by jrtc27** [comment]
Ok, thanks

**Comment by lbmeng** [comment]
> the decision was taken to keep the name as Zhinx

This is confusing as it may indicate it has something to do with the H-ext.

Which position should we put Zhinx in the ISA string?
