### ISSUE TITLE
How to use zfinx in llc?

### ISSUE THREAD

**Issue by hughperkins** [riscv/riscv-zfinx#15]
Hi,

I'm trying to use LLC to compile LLVM IR bytecode into RV32Zfinx. I'm using LLVM-14.0.0, since it looks like zfinx is supported by llvm 14:

```
$ /usr/local/opt/llvm-14.0.0/bin/llc --march riscv32 -mattr=help 2>&1 | grep zfinx
  zfinx            - 'Zfinx' (Float in Integer).
```

Let's focus on compiling a single `fadd`, and prior loads, which in the context of the longer code looks as following in LLVM IR:

```
  %18 = load float, float* %17, align 4
  %19 = load float, float* %7, align 4
  %20 = fadd contract float %19, %18
```

Compile using +zfinx:
```
$ /usr/local/opt/llvm-14.0.0/bin/llc sum_floats-device.ll -o sum_floats-device.s --march=riscv32 -mattr=+zfinx
```

Result is:
```
	lw	a1, 0(a0)
	lw	a0, -28(s0)
	call	__addsf3@plt
```

It's been compiled into `_addsf3@plt`, which is a software emulation. It's the same as what we get if we compile without either `+f` or `+zfinx`:

```
$ /usr/local/opt/llvm-14.0.0/bin/llc sum_floats-device.ll -o sum_floats-device.s --march=riscv32 -mattr=
```
gives
```
	lw	a1, 0(a0)
	lw	a0, -28(s0)
	call	__addsf3@plt
```
(i.e. exactly the same as with `+zfinx`

For comparison, if we use `+f`, we do get an `fadd` call, but float registers are used, which we don't want:

```
$ /usr/local/opt/llvm-14.0.0/bin/llc sum_floats-device.ll -o sum_floats-device.s --march=riscv32 -mattr=+f
```
gives
```
	flw	ft0, 0(a0)
	flw	ft1, -28(s0)
	fadd.s	ft0, ft1, ft0
```

Thoughts? How can I go about compiling using `+zfinx`, in llc?

**Comment by ChunyuLiao** [comment]
hi hughperkins, 
As far as I know, LLVM14 does not support Zfinx. 
LLVM15 only supports llvm-mc, You can try to compile .s files.

llc can not be used, there are some incomplete patchs:
https://reviews.llvm.org/D122918
https://reviews.llvm.org/D121774

**Comment by hughperkins** [comment]
I see. Thanks. I already have an assembler, albeit in python, https://github.com/hughperkins/VeriGPU/blob/main/verigpu/assembler.py . What I need really is the conversion LLVM IR => RISC-V assembler. Ok, I will look into trying to learn TabelGen, and see how far I get. (I should probably ditch my own assembler, and use the llvm one instead :P )

**Comment by hughperkins** [comment]
Turns out there is a patch at https://reviews.llvm.org/D122918 that gets enough stuff working for my own code to run now :)
