### ISSUE TITLE
No need to require software do NaN-boxing

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-zfinx#3]
I don't think we should require software to implement NaN-boxing on loads and moves of floating-point values narrower than XLEN.  When software is properly written (and correctly translated by a compiler), NaN-boxing should be visible only in unusual circumstances, such as when a program examines memory that hasn't been properly initialized, or when using a debugger to view the state of registers or memory.  I would argue these circumstances aren't important enough to insist that software replicate the exact same results for Zfinx.

**Comment by tariqkurd-repo** [comment]
I agree, the spec says how to get consistent behaviour, but you wouldn't actually bother to do it.
Do you want me to weaken the wording to make it more obvious that it's optional?

**Comment by tariqkurd-repo** [comment]
clarified further in the doc as it came up again
