### ISSUE TITLE
Should register pairs always be little-endian order?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-zfinx#4]
Should the order of register pairs (which register contains the upper half and which the lower half of double-wide values) depend on the selected endianness?  It would be better for hardware if register pairs were always in little-endian order, although the big-endian ABIs must be considered too.

**Comment by tariqkurd-repo** [comment]
Hi John, sorry I didn't see this until just now.

In the P-extension they have:

"How the register pair contains the 64-bit value depends on the current data endian represented in mstatus.MBE/SBE/UBE. When the data endian is big, the even “2d” register of the pair contains the high 32-bit of the value and the odd “2d+1” register of the pair contains the low 32-bit of the result. In contrast, when the data endian is little, the odd register of the pair contains the high 32-bit of the result and the even register of the pair contains the low 32-bit of the result."

Zfinx is intended to be compatible with this. Do you think there's a problem with it?

Tariq

**Comment by jhauser-us** [comment]
Apologies for the long delay, but I've been very busy lately with some higher-priority subjects.

I've spoken with Andrew Waterman about this, and we agree that the P extension has it wrong and will need to change.  Register pair order should *not* be affected by the current endianness.  The main reason is that this would be very bad for RISC-V cores that support both little-endian and big-endian byte orders.  Those cores would need muxes to select the low and high halves from each register operand pair ahead of operations.  By fixing the register pair order to be only little-endian, those muxes can be eliminated.

It is true that bi-endian cores might then be forced to swap the word order on loads and stores, if there are ever any instructions to load/store register pairs.  But bi-endian cores already must swap byte order for regular loads and stores of halfwords, words, etc.  And it would be far better to insert these muxes in the load/store path than in the ALU paths.

Without load/store instructions of register pairs (a likely scenario), then it simply falls to software to load/store registers in the correct little-endian pair order, and no extra hardware muxes are needed either for the ALU paths or for memory accesses.

**Comment by tariqkurd-repo** [comment]
Thanks John - I've updated the spec, please check it's ok

**Comment by jhauser-us** [comment]
I believe the table in the NaN-boxing section needs updating to be consistent.

**Comment by tariqkurd-repo** [comment]
ok, done. Thanks!
