### ISSUE TITLE
disassemble confilict

### ISSUE THREAD

**Issue by luxufan** [riscv/riscv-zfinx#5]
for example the (fnmsub.s f18, f19, f20, f21, dyn) instruction and (fnmsub.s x18, x19, x20, x21, dyn) instruction has the same 
encoding, so, how does the disassembler disassemble these two instruction

**Comment by kito-cheng** [comment]
Allocate one bit for zfinx on e_flags should be fine, or ELF attribute is another option, but it's optional section, so I guess e_flags would be more appropriate.

https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#-file-header

**Comment by luxufan** [comment]
Thanks, Kito. I have a question that if zfinx is enabled, are there float registers?

**Comment by tariqkurd-repo** [comment]
If zfinx is enabled there are no float registers.
I agree there should be something in the ELF header, I'll check with Jiawei on the mailing list.

**Comment by tariqkurd-repo** [comment]
the newly formed psABI group will resolve this issue

**Comment by tariqkurd-repo** [comment]
closed via https://github.com/riscv/riscv-elf-psabi-doc/issues/166
