### ISSUE TITLE
Nan-Boxing for RV64F

### ISSUE THREAD

**Issue by luxufan** [riscv/riscv-zfinx#7]
assue the hardware is RV64F: 
```
lw[u] x1, 0(sp)   # load 32-bits into x1 and sign / zero extend upper 32-bits
fadd.s x1, x1, x1 # use x1 but do not check source is Nan-boxed, NaN-box output
```
the lw instruction will sign/zero extend upper 32-bits instead of set all 1 in upper 32-bits(which needs for Nan-Boxing).
so the problem is that if it is necessary to generate instructions by compilers to set all 1 in the upper 32-bits of x1 after the lw[u] x1, 0(sp).

**Comment by tariqkurd-repo** [comment]
Hi Luxufan, the NaN boxing isn't required because the fadd.s doesn't check for it on the source operands, so the compiler doesn't need to worry about it.

**Comment by luxufan** [comment]
> Hi Luxufan, the NaN boxing isn't required because the fadd.s doesn't check for it on the source operands, so the compiler doesn't need to worry about it.

But in the replaced instruction part of the spec, for RV64F, the flw instruction was replaced by lw and Nan-boxing in software. So, if the instructions that don't check the NaN-boxing for source operand (like fadd.s), then, the flw can be replaced by lw. But if the instructions that check the NaN-boxing, then the compiler need a software NaN-boxing. Is it right ? And is all of the f instruction don't check the NaN-boxing for source operand?

**Comment by tariqkurd-repo** [comment]
HI Luxufan, I've updated section 9 in the doc to clarify that the compiler doesn't need to Nan_box. Is that OK for you?

**Comment by luxufan** [comment]
> HI Luxufan, I've updated section 9 in the doc to clarify that the compiler doesn't need to Nan_box. Is that OK for you?

OK! Thanks
