### ISSUE TITLE
Zfinx cannot be an extension to F

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-zfinx#8]
Zfinx removes the floating-point registers and reuses the integer registers. Code written for RVF uses floating-point registers, and is written against a *ratified standard*. Having Zfinx be an extension of F violates that, and is therefore not permitted; code written for any arbitrary subset of the extensions specified *must* continue to work, otherwise the extensions are not compatible. Thus Zfinx *must* be mutually exclusive with F.

**Comment by tariqkurd-repo** [comment]
Hi - sorry I didn't seem to get a notification for this.
I'm not sure what you're worried about - where does it say that Zfinx is "an extension of F"

**Comment by jrtc27** [comment]
The spec talks about "RV32IFD Zfinx" and all other variants everywhere. Such an ISA string should not be valid when using Zfinx due to the above issue; F and Zfinx *must* be mutually exclusive.

**Comment by tariqkurd-repo** [comment]
How can RV32IFD Zfinx not be valid when using Zfinx? There's a major disconnect here, and I have no idea what this complaint is about or what you're are getting at. At least tell me what your interest is in Zfinx so I have something to go on?

**Comment by jrtc27** [comment]
RV32IFDZfinx means that the F, D and Zfinx extensions are all present. But Zfinx and F cannot both be present at the same time, since they use different register sets.

**Comment by jrtc27** [comment]
As for my interest in Zfinx, I don't care about it, beyond the fact that I'm an upstream LLVM developer and maintain a downstream fork for a significant non-standard RISC-V extension. As such I end up reviewing RISC-V patches for upstream LLVM and thus discovered that Zfinx violates a core principle of extensions in RISC-V, so do not want to see such a thing land in LLVM and break code that complies to ratified standards, as that would be a disservice to every user out there.

**Comment by jrtc27** [comment]
i.e. RV32IF is valid and RV32IZfinx is valid, but RV32IFZfinx is invalid due to the conflicting specification for all the floating-point instructions between F and Zfinx. For D and Q you need separate Zdinx and Zqinx extension names, but again they cannot be combined with F (nor FD/FDQ).

**Comment by tariqkurd-repo** [comment]
Ok, that makes more sense as you've given me some context now. I'll look at this on Monday.

**Comment by tariqkurd-repo** [comment]
From the point of view of the spec, not the LLVM implementation (which I don't work on), is the problem specifying the configuration like this: rv32_Zfhbase_Zffbase_Zfdbase_Zfma_Zfdiv_Zfinx? 

Do you want this to be specified differently, e.g: 

rv32_ZfhbaseZfinx_ZffbaseZfinx_ZfdbaseZfinx_ZfmaZfinx_ZfdivZfinx

so each part is modified to be the Zfinx version?

**Comment by jim-wilson** [comment]
Extensions are supposed to be purely additive.

So for instance B is defined as zbb+zba+zbc+zbs.  So rv32ib and rv32i_zbb are OK, but rv32ib_zbb is redundant and non-canonical and potentially confusing as B already includes Zbb and perhaps should not be allowed.

We could say that zfinx is the F instruction set and zfreg is the F register set, and then F can be defined as zfinx+zfreg.  If we do this, then rv32if_zfinx makes no sense, as F includes the register set.  It is only rv32i_zfinx that makes sense.  Also, if we do this, then we need zdinx for the D instruction set and zdreg for the D register set.  But zfreg and zdreg are useless by themselves as I can't see anyone adding the FP register sets without the FP instructions, so it isn't clear that doing things this way has any use.  Also, if we do things this way, then zfinx is not necessarily the right name, maybe something like zfinstr to indicate that it is the F instructions,  Then F=zfinstr+zfreg makes more sense.

I'd suggest bumping it up to the ISA group and asking them if they want to redefine what F means, or allow a minor exception for zfinx, or maybe just say that zfinx is its own extension separate and conflicting with F which means rv32i_zfinx is correct and rv32if_zfinx is not allowed.  Anyways, I think it is an issue to be decided higher up.

**Comment by tariqkurd-repo** [comment]
My current proposal is this, I'm trying to get it approved:

F + Zfinx = ZfinxF (incompatible with F)
D + Zfinx = ZfinxD (which implies ZfinxF)
Q + Zfinx = ZfinxQ (which implies ZfinxD and ZfinxF)
Zfh + Zfinx = ZfinxZfh (which implies ZfinxF)

So if you want Zfh + F + D + Zfinx you need to specify ZfinxZfh_ZfinxD

And also we need:

V + Zfinx = ZfinxV

So [FDQV]_Zfinx* is illegal, as they are incompatible

…and any future extensions which use the F registers will need a Zfinx version…

**Comment by tariqkurd-repo** [comment]
@jrtc27 I've made a big update to the spec, please review it.

**Comment by jrtc27** [comment]
I think that's fine now, except for the fact that the spec is still saying `misa.F` should be 1 (in §4 Discovery), which is specified by the existing riscv-isa-manual to mean the F extension is present, so it can't be used for Zfinx (ditto `misa.[DQ]`, though the Zfinx spec doesn't say anything about those currently).

**Comment by tariqkurd-repo** [comment]
hmm that's awkward, because it means Zfinx now needs its own discovery mechanism instead of stealing the one specified by misa.[FDQ]. I wonder how the existance of Zfh is specified....... I'll get back to you......

**Comment by jrtc27** [comment]
`misa` doesn't scale. The answer is probably "check the device tree" (or ask your firmware).

**Comment by tariqkurd-repo** [comment]
Zfh (half-precision FP) isn't in MISA AFAIK, so I'll find out what that does and do the same. There's normally a hardware method of detecting extensions. I'll get back to you.

**Comment by tariqkurd-repo** [comment]
I'll close this now. I'm waiting for a standard method of detecting extensions to be defined via a new CSR before I can complete this spec. but this issue is now resolved.
