### ISSUE TITLE
Interoperation with V extension

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-zfinx#9]
The specification says:

_This does not affect floating point instructions that are implemented as part of the Vector (v) extension._

I don't think this is workable. The V extension has a large number of instructions that have scalar floating point registers as operands; presumably, these will all have to change to take input from (or write results to) X registers instead. There are also load, store and move instructions that may need to be omitted for consistency with scalar floating point instructions as described here.

**Comment by tariqkurd-repo** [comment]
You're right - we need to solve https://github.com/riscv/riscv-zfinx/issues/8 and then the interaction with the V-extension will also be specified

**Comment by tariqkurd-repo** [comment]
OK, I removed the statement about the V-extension. there'll be a further update regarding Zfinx+V when I resolve issue 8, but I think I can close this issue now.

**Comment by JamesKenneyImperas** [comment]
For future reference, I think the V extension floating point instructions that might be removed for consistency with scalar Zfinx are:
- `vfmerge.vfm` (equivalent to `vmerge.vxm`)
- `vfmv.v.f` (equivalent to `vmv.v.x`)

**Comment by tariqkurd-repo** [comment]
vfmv.v.f -> vmv.v.x
vfmv.f.s -> vmv.x.s
vfmv.s.f -> vmv.s.x
vfmerge.vfm -> vmerge.vxm

but also all of these will use an X source for rs1 instead of an F source

vmfeq.vf vd, vs2, rs1, vm  # vector-scalar 
vmfne.vf vd, vs2, rs1, vm  # vector-scalar
vmflt.vv vd, vs2, vs1, vm  # Vector-vector
vmflt.vf vd, vs2, rs1, vm  # vector-scalar
vmfle.vv vd, vs2, vs1, vm  # Vector-vector
vmfle.vf vd, vs2, rs1, vm  # vector-scalar
vmfgt.vf vd, vs2, rs1, vm  # vector-scalar
vmfge.vf vd, vs2, rs1, vm  # vector-scalar

vfmin.vf vd, vs2, rs1, vm   # vector-scalar
vfmax.vf vd, vs2, rs1, vm   # vector-scalar

vfsgnj.vf vd, vs2, rs1, vm   # vector-scalar
vfsgnjn.vf vd, vs2, rs1, vm  # vector-scalar
vfsgnjx.vf vd, vs2, rs1, vm  # vector-scalar

**Comment by tariqkurd-repo** [comment]
https://github.com/riscv/riscv-zfinx/blob/master/Zfinx_spec.adoc#vector

please check it! thanks.

**Comment by jnk0le** [comment]
There are definitely more OPFVF opcodes. riscv/riscv-v-spec/blob/master/inst-table.adoc

and a few typos:
>Vector-vector

**Comment by JamesKenneyImperas** [comment]
Yes, @jnk0le is right, there are many more; anything with a `.vf` suffix is also candidate. That instruction table is pretty hard to comprehend, unfortunately. Here is a stab at the `.vf` instructions:

```
    vfadd.vf
    vfsub.vf
    vfrsub.vf
    vfmin.vf
    vfmax.vf
    vfsgnj.vf
    vfsgnjn.vf
    vfsgnjx.vf
    vfslide1up.vf
    vfslide1down.vf
    vmfeq.vf
    vmfle.vf
    vmflt.vf
    vmfne.vf
    vmfgt.vf
    vmfge.vf
    vfdiv.vf
    vfrdiv.vf
    vfmul.vf
    vfrsub.vf
    vfmadd.vf
    vfnmadd.vf
    vfmsub.vf
    vfnmsub.vf
    vfmacc.vf
    vfnmacc.vf
    vfmsac.vf
    vfnmsac.vf
    vfwadd.vf
    vfwsub.vf
    vfwadd.w.f
    vfwsub.w.f
    vfwmul.vf
    vfwmacc.vf
    vfwnmacc.vf
    vfwmsac.vf
    vfwnmsac.vf

```

**Comment by JamesKenneyImperas** [comment]
I wonder whether it is actually necessary to explicitly list all the scalar floating point vector instructions at all here? The important thing from an implementation perspective is the four _deleted_ instructions, which clearly must be listed. I think all the others could be covered by a general statement about floating point scalar operands and a link to instruction table in the Vector specification.

**Comment by tariqkurd-repo** [comment]
Yes, I hadn't found the instruction table document before. You're both right, thanks.
I've explicitly listed the 4 deletions and said if funct3=OVFPF then access an X register instead of an F register.
is it ok now?

**Comment by JamesKenneyImperas** [comment]
Yes, I think this works for me.

**Comment by tariqkurd-repo** [comment]
great, let me know if there are any more problems!

**Comment by JamesKenneyImperas** [comment]
Hi Tariq,

One more minor pedantic point: on RV32GCV hardware with Zfinx, the floating point values will be in X register pairs, so perhaps the last sentence could say:

Additionally, all instructions with funct3=OPFVF take the source from an X register _or even/odd X register pair_ instead of an F register.

**Comment by tariqkurd-repo** [comment]
Hi James, where is this stated in the vector spec?
